# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqSPgyOZwO5lSxlDyFfDPfWZQIXXgbOO
"""

!pip install folium geopy geopandas osmnx networkx scikit-learn
print("Cài đặt xong thư viện!")

import folium
from geopy.distance import geodesic

center = (10.7613, 106.6687)
m = folium.Map(location=center, zoom_start=14)

locations = [
    {"name": "Bệnh viện Chợ Rẫy", "coords": (10.7573, 106.6575)},
    {"name": "Vạn Hạnh Mall", "coords": (10.7706, 106.6713)},
    {"name": "UBND Quận 10", "coords": (10.7712, 106.6661)},
    {"name": "Bến xe Lê Hồng Phong", "coords": (10.7635, 106.6738)},
    {"name": "Ký túc xá UEH", "coords": (10.7600, 106.6650)}
]

layer_center = folium.FeatureGroup(name="Trung tâm").add_to(m)
layer_pois = folium.FeatureGroup(name="Các điểm lân cận").add_to(m)

folium.Marker(center, popup="Điểm trung tâm", icon=folium.Icon(color='red')).add_to(layer_center)

for loc in locations:
    dist = geodesic(center, loc["coords"]).kilometers
    folium.Marker(
        loc["coords"],
        popup=f"{loc['name']}<br>Cách tâm: {dist:.2f}km"
    ).add_to(layer_pois)

folium.LayerControl().add_to(m)
m

import numpy as np
from folium.plugins import HeatMap

m2 = folium.Map(location=center, zoom_start=13)

heat_data = [[10.761 + np.random.normal(0, 0.02), 106.668 + np.random.normal(0, 0.02)] for _ in range(300)]
HeatMap(heat_data, radius=12).add_to(m2)

folium.Circle(center, radius=3000, color='green', weight=2, fill=False, tooltip="Vùng 3km").add_to(m2)
folium.Circle(center, radius=5000, color='orange', weight=2, fill=False, tooltip="Vùng 5km").add_to(m2)
folium.Circle(center, radius=10000, color='red', weight=2, fill=False, tooltip="Vùng 10km").add_to(m2)

m2

import geopandas as gpd
import osmnx as ox
import matplotlib.pyplot as plt
import random

print("Đang tải dữ liệu ranh giới bằng GeoPandas/OSMnx...")
districts = ox.geocode_to_gdf(["Quận 1, Ho Chi Minh City", "Quận 3, Ho Chi Minh City", "Quận 10, Ho Chi Minh City", "Quận 5, Ho Chi Minh City"])

districts['don_hang'] = [random.randint(1000, 5000) for _ in range(len(districts))]

fig, ax = plt.subplots(1, 1, figsize=(8, 6))
districts.plot(column='don_hang', cmap='OrRd', legend=True,
               edgecolor='black', ax=ax,
               legend_kwds={'label': "Số lượng đơn hàng"})

plt.title("Bài 23.4: Bản đồ Choropleth theo ranh giới Quận")
plt.axis('off')
plt.show()

import osmnx as ox
import networkx as nx

print("Đang tải dữ liệu đường phố thật (Bán kính 800m)...")
G = ox.graph_from_point(center, dist=800, network_type="drive")

nodes = list(G.nodes())
start_node = nodes[10]
end_node = nodes[-10]

shortest_path = nx.shortest_path(G, source=start_node, target=end_node, weight='length')

fig, ax = ox.plot_graph_route(G, shortest_path, route_color='red', route_linewidth=4, node_size=2)

import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np

coords = np.random.rand(50, 2) * 10

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10).fit(coords)
kho_hang = kmeans.cluster_centers_

df_donhang = pd.DataFrame(coords, columns=['Vĩ độ', 'Kinh độ'])
df_donhang['Mã Trạm Gán'] = kmeans.labels_

print("Bảng gán xe mô phỏng (Bài 23.8):")
print(df_donhang.head(10))

plt.figure(figsize=(7, 5))
plt.scatter(coords[:, 0], coords[:, 1], c=kmeans.labels_, cmap='tab10', alpha=0.7, label='Điểm giao')
plt.scatter(kho_hang[:, 0], kho_hang[:, 1], c='red', marker='s', s=150, label='Trạm/Kho (AI đề xuất)')
plt.title("Bài 23.8 & 23.9: Phân cụm và Gán trạm bằng K-Means")
plt.legend()
plt.show()

import networkx as nx
import matplotlib.pyplot as plt
import random

print("🚦 Đang phân tích rủi ro kẹt xe (Bài 23.10)...")
G = nx.grid_2d_graph(5, 5)

for u, v in G.edges():
    G.edges[u, v]['weight'] = 1

ket_xe_edges = random.sample(list(G.edges()), 5)
for u, v in ket_xe_edges:
    G.edges[u, v]['weight'] = 10

start, end = (0, 0), (4, 4)

duong_ngan_nhat = nx.shortest_path(G, start, end)

duong_toi_uu = nx.shortest_path(G, start, end, weight='weight')

plt.figure(figsize=(8, 6))
pos = {(x, y): (y, -x) for x, y in G.nodes()}

nx.draw(G, pos, node_color='lightgray', node_size=200, edge_color='gray')
nx.draw_networkx_edges(G, pos, edgelist=ket_xe_edges, edge_color='red', width=4, label='Kẹt xe')
nx.draw_networkx_edges(G, pos, edgelist=[(duong_toi_uu[i], duong_toi_uu[i+1]) for i in range(len(duong_toi_uu)-1)], edge_color='green', width=4, label='Đường vòng thay thế')

plt.title("Bài 23.10: Mô hình AI tránh kẹt xe")
plt.legend(['Đường bình thường', 'Rủi ro kẹt xe', 'Tuyến đường đề xuất'])
plt.axis('off')
plt.show()

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import folium

print("📈 Đang chạy mô hình ML dự đoán nhu cầu (Bài 23.11)...")

data = []
for _ in range(500):
    lat = 10.76 + np.random.uniform(-0.02, 0.02)
    lon = 106.66 + np.random.uniform(-0.02, 0.02)
    hour = np.random.randint(6, 22)
    rain = np.random.randint(0, 2)
    demand = int((hour == 17) * 50 + rain * 80 + np.random.randint(10, 30))
    data.append([lat, lon, hour, rain, demand])

df = pd.DataFrame(data, columns=['Lat', 'Lon', 'Hour', 'Rain', 'Demand'])

X = df[['Lat', 'Lon', 'Hour', 'Rain']]
y = df['Demand']
model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(X, y)

m_predict = folium.Map(location=[10.76, 106.66], zoom_start=14)
test_points = df.sample(20)[['Lat', 'Lon']]
test_points['Hour'] = 17
test_points['Rain'] = 1
test_points['Predicted_Demand'] = model.predict(test_points[['Lat', 'Lon', 'Hour', 'Rain']])

for _, row in test_points.iterrows():
    color = 'red' if row['Predicted_Demand'] > 100 else 'orange' if row['Predicted_Demand'] > 50 else 'green'
    folium.CircleMarker(
        location=[row['Lat'], row['Lon']],
        radius=row['Predicted_Demand'] /
        color=color, fill=True,
        popup=f"Dự báo nhu cầu: {int(row['Predicted_Demand'])} yêu cầu"
    ).add_to(m_predict)

display(m_predict)
print("-> Khu vực chấm đỏ cần điều tiết thêm nhân sự/xe cộ ngay lập tức.")

from scipy.spatial import distance_matrix

print("🚚 Đang chạy thuật toán Tối ưu hóa điều phối (Bài 23.12)...")
locations = np.random.rand(11, 2) * 10
kho = locations[0]
khach_hang = locations[1:]

plt.figure(figsize=(8, 6))
plt.scatter(khach_hang[:, 0], khach_hang[:, 1], c='blue', label='Khách hàng')
plt.scatter(kho[0], kho[1], c='black', marker='s', s=200, label='Kho trung tâm')

xe_1 = [i for i in range(1, 11) if locations[i][0] < 5]
xe_2 = [i for i in range(1, 11) if locations[i][0] >= 5]

def draw_route(vehicle_nodes, color, label):
    if not vehicle_nodes: return
    current = 0
    unvisited = vehicle_nodes.copy()
    route_x, route_y = [locations[current][0]], [locations[current][1]]

    while unvisited:
        next_node = min(unvisited, key=lambda x: np.linalg.norm(locations[current] - locations[x]))
        route_x.append(locations[next_node][0])
        route_y.append(locations[next_node][1])
        unvisited.remove(next_node)
        current = next_node

    route_x.append(locations[0][0])
    route_y.append(locations[0][1])
    plt.plot(route_x, route_y, c=color, linewidth=2, marker='o', label=label)

draw_route(xe_1, 'orange', 'Lộ trình Xe 1')
draw_route(xe_2, 'purple', 'Lộ trình Xe 2')

plt.title("Bài 23.12: Giải bài toán VRP (Heuristic)")
plt.legend()
plt.show()

import time
from IPython.display import clear_output

trucks = pd.DataFrame({
    'Xe': ['Xe 01', 'Xe 02', 'Xe 03', 'Xe 04', 'Xe 05'],
    'Tiến độ (%)': [10, 25, 5, 40, 15],
    'Trạng thái': ['Đang đi', 'Đang đi', 'Kẹt xe', 'Gần đến', 'Đang đi']
})

print("🖥️ ĐANG CẬP NHẬT DASHBOARD REAL-TIME (Mô phỏng)...")

for i in range(5):
    clear_output(wait=True)
    trucks['Tiến độ (%)'] += np.random.randint(5, 15, size=5)
    trucks.loc[trucks['Tiến độ (%)'] > 100, 'Tiến độ (%)'] = 100

    print(f"--- BÁO CÁO HỆ THỐNG GIÁM SÁT (Lần cập nhật {i+1}) ---")
    print(trucks.to_string(index=False))

    plt.barh(trucks['Xe'], trucks['Tiến độ (%)'], color='skyblue')
    plt.xlabel("Tiến độ hoàn thành (%)")
    plt.xlim(0, 100)
    plt.show()

    time.sleep(1)

print("💡 ĐỀ XUẤT GIẢI PHÁP: HỆ THỐNG ĐIỀU PHỐI Ô DÙ THÔNG MINH (SHAREBRELLA)")
print("-" * 60)
print("1. CÔNG NGHỆ: Sử dụng cảm biến IoT tại trạm và AI dự báo thời tiết.")
print("2. THUẬT TOÁN: Dùng K-Means (Bài 23.9) để xác định vị trí đặt trạm dư thừa dù.")
print("3. ĐIỀU PHỐI: Khi trạm A sắp hết dù, thuật toán Dijkstra (Bài 23.7) sẽ tìm")
print("   đường ngắn nhất để Robot hoặc nhân viên mang dù từ trạm B đến.")
print("4. GIÁ TRỊ: Giảm 40% tình trạng sinh viên thiếu dù khi trời mưa bất chợt tại UEH.")
print("-" * 60)